### ISSUE TITLE
kafka 이상현상

### ISSUE THREAD

**Issue by JooYeonPark** [hajula-pjt/hejula-server#2]
** 버그 설명 **
kafka가 동작하고 있으나 클러스터링되지 않고 제대로 동작하지 않는 현상 발생

** 발생 상황 설명 **
container restart 하려고 했으나, 동작되지 않음 

**예상된 결과**

**Screenshots**
![image](https://user-images.githubusercontent.com/22074405/129431589-5644abc7-0f43-4aab-b84e-42eb8bbd4595.png)

kafka1의 log
`[2021-08-11 06:53:17,910] ERROR Error while writing to checkpoint file /var/lib/kafka/data/replication-offset-checkpoint (kafka                           .server.LogDirFailureChannel)
java.io.FileNotFoundException: /var/lib/kafka/data/replication-offset-checkpoint.tmp (No space left on device)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:94)
        at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:92)
        at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:67)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7(ReplicaManager.scala:1813)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$7$adapted(ReplicaManager.scala:1813)
        at scala.Option.foreach(Option.scala:437)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6(ReplicaManager.scala:1813)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6$adapted(ReplicaManager.scala:1812)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
        at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1812)
        at kafka.server.ReplicaManager.$anonfun$startHighWatermarkCheckPointThread$1(ReplicaManager.scala:301)
`

docker 컨테이너 정보
![image](https://user-images.githubusercontent.com/22074405/129431666-707c5c65-2c3a-477e-ad5f-6f258613e423.png)

container stop 불가
![image](https://user-images.githubusercontent.com/22074405/129431681-2e3f371e-ebbf-4b05-97d0-b81e2f2b108d.png)

**추가정보**

**Comment by JooYeonPark** [comment]
container 삭제 후 재 설정
